name: mlforecast
channels:
  - conda-forge
dependencies:
  - black
  - dask<2023.1.1
  - duckdb<0.8
  - flake8
  - jupyterlab
  - lightgbm
  - matplotlib
  - mypy
  - numba
  - pandas
  - pip
  - pylint
  - pyspark>=3.3
  - scikit-learn
  - window-ops
  - xgboost
  - pip:
    - datasetsforecast
    - fugue[ray]
    - lightgbm_ray
    - nbdev
    - ray<2.4
    - xgboost_ray
