name: mlforecast
channels:
  - conda-forge
dependencies:
  - dask<2023.1.1
  - lightgbm
  - matplotlib
  - nbformat
  - numba
  - pandas
  - pip
  - prophet
  - pyspark>=3.3
  - scikit-learn
  - statsmodels
  - utilsforecast
  - window-ops
  - xgboost
  - pip:
    - datasetsforecast
    - duckdb<0.8
    - fugue[ray]
    - lightgbm_ray
    - nbdev
    - ray<2.4
    - xgboost_ray
