name: mlforecast
channels:
  - conda-forge
dependencies:
  - dask<2023.1.1
  - fsspec
  - gitpython
  - holidays<0.21
  - lightgbm
  - matplotlib
  - nbformat
  - numba
  - pandas
  - pip
  - prophet
  - pyarrow
  - pyspark>=3.3
  - s3fs
  - scikit-learn
  - shap
  - statsmodels
  - window-ops
  - py-xgboost-cpu
  - pip:
    - datasetsforecast
    - duckdb<0.8
    - fugue[ray]
    - lightgbm_ray
    - nbdev
    - polars
    - ray<2.8
    - triad==0.9.1
    - utilsforecast>=0.0.27
    - xgboost_ray
