name: mlforecast
channels:
  - conda-forge
dependencies:
  - lightgbm
  - matplotlib
  - nbformat
  - numba
  - pandas
  - pip
  - scikit-learn
  - statsmodels
  - utilsforecast
  - window-ops
  - xgboost
  - pip:
    - datasetsforecast
    - nbdev
