name: mlforecast
channels:
  - conda-forge
dependencies:
  - holidays<0.21
  - lightgbm
  - matplotlib
  - nbformat
  - numba
  - pandas
  - pip
  - prophet
  - scikit-learn
  - shap
  - statsmodels
  - window-ops
  - xgboost
  - pip:
    - datasetsforecast
    - nbdev
    - utilsforecast>=0.0.8
