name: mlforecast
channels:
  - conda-forge
dependencies:
  - lightgbm
  - matplotlib
  - nbformat
  - numba
  - pandas
  - pip
  - scikit-learn
  - statsforecast
  - window-ops
  - xgboost
  - pip:
    - datasetsforecast
    - nbdev
    - prophet
