name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash -l {0}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: 0.7.14
          channels: conda-forge
          activate-environment: mlforecast
          environment-file: environment.yml
          use-only-tar-bz2: true

      - name: Install action requirements and the library
        run: pip install nbdev mypy flake8 isort matplotlib tabulate ./

      - name: Lint
        run: flake8 --select=F mlforecast/ && mypy mlforecast/ && isort --check-only mlforecast/

      - name: Read all notebooks
        run: nbdev_read_nbs

      - name: Check if all notebooks are cleaned
        run: |
          echo "Check we are starting with clean git checkout"
          if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
          echo "Trying to strip out notebooks"
          nbdev_clean_nbs
          echo "Check that strip out was unnecessary"
          git status -s # display the status to see which nbs need cleaning up
          if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_git_hooks"; false; fi

      - name: Check if there is no diff library/notebooks
        run: |
          if [ -n "$(nbdev_diff_nbs)" ]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi

      - name: Run tests
        run: nbdev_test_nbs --n_workers 1

  test-cli-extra:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install library with extra
        working-directory: mlforecast
        run: pip install ".[cli]" pyarrow

      - name: Run CLI
        working-directory: mlforecast
        run: |
          python action_files/create_data.py
          mlforecast sample_configs/local.yaml
          if [ ! -f 'data/outputs/forecast.parquet' ]; then false; fi
          rm -rf data

    test-cli-and-distributed-extras:
      runs-on: ubuntu-latest
      steps:
        - name: Clone repo
          uses: actions/checkout@v2

        - name: Set up python
          uses: actions/setup-python@v2
          with:
            python-version: 3.7

        - name: Install library with extra
          working-directory: mlforecast
          run: pip install ".[cli, distributed]" pyarrow

        - name: Run CLI
          working-directory: mlforecast
          run: |
            python action_files/create_data.py --distributed
            mlforecast sample_configs/distributed.yaml
            if [ ! -d 'data/outputs/forecast/' ]; then false; fi
            rm -rf data
