name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

defaults:
  run:
    shell: bash -l {0}

jobs:
  nb-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2

      - name: Install nbdev
        run: pip install nbdev

      - name: Read all notebooks
        run: nbdev_read_nbs

      - name: Check if all notebooks are cleaned
        run: |
          echo "Check we are starting with clean git checkout"
          if [ -n "$(git status -uno -s)" ]; then echo "git status is not clean"; false; fi
          echo "Trying to strip out notebooks"
          nbdev_clean_nbs
          echo "Check that strip out was unnecessary"
          git status -s # display the status to see which nbs need cleaning up
          if [ -n "$(git status -uno -s)" ]; then echo -e "!!! Detected unstripped out notebooks\n!!!Remember to run nbdev_install_git_hooks"; false; fi

      - name: Check if there is no diff library/notebooks
        run: |
          if [ -n "$(nbdev_diff_nbs)" ]; then echo -e "!!! Detected difference between the notebooks and the library"; false; fi

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2

      - name: Install linters
        run: pip install mypy flake8 isort

      - name: Lint
        run: flake8 --select=F mlforecast/ && mypy mlforecast/ && isort --check-only mlforecast/

  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.6, 3.7, 3.8]
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: 0.7.14
          channels: conda-forge
          activate-environment: mlforecast
          environment-file: environment.yml

      - name: Install action requirements and the library
        run: pip install nbdev matplotlib tabulate ./

      - name: Run all tests
        if: matrix.os == 'ubuntu-latest'
        run: nbdev_test_nbs --n_workers 1

      - name: Run local tests
        if: matrix.os != 'ubuntu-latest'
        run: cd nbs/ && nbdev_test_nbs --fname "[!da]*"

  test-cli-extra:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install library with extra
        run: pip install ".[cli]" pyarrow scikit-learn

      - name: Run CLI
        run: |
          python action_files/create_data.py
          mlforecast sample_configs/local.yaml
          if [ ! -f 'data/outputs/forecast.parquet' ]; then false; fi

  test-cli-and-distributed-extras:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install library with extra
        run: pip install ".[cli, distributed]" pyarrow scikit-learn xgboost

      - name: Run CLI
        run: |
          python action_files/create_data.py --distributed
          mlforecast sample_configs/distributed.yaml
          if [ ! -d 'data/outputs/forecast/' ]; then false; fi
